version: '2'
services:
  parser:
    image: nginx
    container_name: nginx
    ports:
    - 8009:80
    logging:
      driver: gelf
      options:
        gelf-address: "udp://192.168.2.237:12201"
        tag: "nginx"
